### ISSUE TITLE
Kelvin adjustment in home app

### ISSUE THREAD

**Issue by FalconEVO** [devbobo/homebridge-lifx-lan#12]
I am currently using this plugin to control my white bulbs via the home app. It is working well for brightness, but has no way of adjusting kelvin. It looks like this is supposed to be a supported feature, but I wanted to check before I dig into things too far.

Thanks!

**Comment by devbobo** [comment]
@FalconEVO I don't have access to the thread but Lifx themselves said that Kelvin setting is kind of a calculated field, a mix of saturation, color and brightness.

The Home app supports a whites type setting but not in the sense of settings kelvin value.

If you go into the Color setting in the Home, and click the Edit button in the middle. A new screen is shown with "Colour" and "Temperature" tabs. The temperature tab is the one where you set a tradition type kelvin-ish setting but with a colour wheel not a value. 

I've actually been considering removing the Kelvin value or at least adding it by default.

Hope that helps.

**Comment by FalconEVO** [comment]
![img_1489](https://cloud.githubusercontent.com/assets/22872090/19456498/4b1f5d8e-9487-11e6-9643-64c852b3194e.PNG)
![img_1488](https://cloud.githubusercontent.com/assets/22872090/19456416/f2d22d1e-9486-11e6-8eaa-6dccd870d6cb.PNG)

The only setting I see is brightness.

**Comment by steve228uk** [comment]
:+1: For this. It seems like the white only bulbs don't get the colour adjustment and not seeing a setting to enable it.

**Comment by devbobo** [comment]
I don't have any white bulbs to test, I may need to pick one up.

**Comment by steve228uk** [comment]
I believe it may be due to the lack of `Characteristic.Saturation` not being included for the white bulbs in `Index.js`. I'm currently building a plugin for another platform and without that the colour wheel will not show even if hue is set.

**Comment by devbobo** [comment]
@steve228uk i suspected as much, I've ordered a white bulb and it should be there early next week when I get home from the US

**Comment by fiddypal** [comment]
I am having the same problem. Can turn bulbs on/off and varying percents using Siri or the home app just fine. But do not have a color option and Siri does not understand when I ask to change color or degree. These are color bulbs and I am forced to use the LIFX app at the moment for colors.

**Comment by devbobo** [comment]
I chatted with `khaost` about this issue, apparently the home app is using a `HSB` value to simulate `color temperature` (aka `Kelvin`). So that option will never appear if the `hue` characteristic isn't defined.

**Comment by vertig0gitrev** [comment]
@devbobo - Any luck on how we generate the config?

**Comment by devbobo** [comment]
@FalconEVO @steve228uk @fiddypal @vertig0gitrev version `0.2.4` should resolve this issue. Color temperature is now supported, though I should mention that the Home app/HomeKit defines ColorTemperature in mireds rather than kelvin....so you will need to work out the mapping from kelvin to mireds if you want to give siri a specific value

https://en.wikipedia.org/wiki/Mired
