### ISSUE TITLE
(question) Manually specifying lifx bulbs

### ISSUE THREAD

**Issue by cmsimike** [devbobo/homebridge-lifx-lan#13]
Hi,

I am excited to see a homebridge lifx plugin that allows more granular control of the bulbs using homekit! My current setup is a bit unorthidox as I needed to put the Lifx bulbs on their own wireless network to prevent them from going offline. While autodetection does not currently work since the Lifx bulbs are on a separate subnet, I can, however, address them individually as long as I specify the IP of each bulb.

Lookin through the docs and code, I did not instantly see a method to specify the IPs of these bulbs. I am hoping I missed something?

**Comment by cmsimike** [comment]
Maybe I can muck with the broadcast address. I feel like I've done this before but it didn't work, but I will give it a go!

**Comment by devbobo** [comment]
@cmsimike check out [node-lifx](https://github.com/MariusRumpf/node-lifx), that's the module I'm using for the low level control of the bulbs. I'm passing through most of the initialisation variables, but there might be something to get it working the way you want.

If i'm missing anything, I'm happy to make changes.
