### ISSUE TITLE
Access to Hue/Saturation missing A19 bulb

### ISSUE THREAD

**Issue by gregorfd** [devbobo/homebridge-lifx-lan#16]
Not able to adjust hue or saturation after install.  using color lifx lights --> LIFX (A19) Wi-Fi Smart LED Light Bulb, Adjustable, Multicolor, Dimmable.

Has this been tested w/the latest lifx bulbs?

**Comment by fiddypal** [comment]
Same here, model # LHA19E26UC10.
 Pretty sure mine is not a gen 3 bulb, this was the older model on sale for 45$ right now.

**Comment by devbobo** [comment]
I've only just got some of the latest bulbs and `node-lifx` has only just been updated to support them, hopefully I'll get a new version out some time this week.

**Comment by devbobo** [comment]
@fiddypal did you buy one of the `white` bulbs ?

**Comment by fiddypal** [comment]
![img_0088](https://cloud.githubusercontent.com/assets/13352552/20691610/1abcbe36-b5a0-11e6-8e76-a293b5aab13b.PNG)
![image](https://cloud.githubusercontent.com/assets/13352552/20691621/2541052e-b5a0-11e6-85bf-fe4645cc6eab.jpg)

Nope they are color I have them on as reddish right now but had to do so using the LIFX app and not apple HomeKit app.

**Comment by fiddypal** [comment]
All I can do is adjust brightness and do on/off from HomeKit (which is better than nothing). But it would be ideal if I can use home app to do all features so I don't have to bounce between apps.
![img_0090](https://cloud.githubusercontent.com/assets/13352552/20691719/d4d469ea-b5a0-11e6-9610-9e36290ea4bb.PNG)

**Comment by devbobo** [comment]
@fiddypal which specific LIFX bulbs do you have ? Model number

**Comment by fiddypal** [comment]
![image](https://cloud.githubusercontent.com/assets/13352552/20691859/f1b8a3a4-b5a1-11e6-8b9f-f86789a9ec5e.jpg)
![image](https://cloud.githubusercontent.com/assets/13352552/20691868/fca324ec-b5a1-11e6-9827-0b774cb20853.jpg)

LHA19E26UC10

**Comment by gregorfd** [comment]
Mine are LiFX LHA19E26UC10

**Comment by devbobo** [comment]
I just released `version 0.1.8` which should address this, you may have to reset homebridge for it to work correctly. Otherwise, use `Hesperus` to remove the accessories. I'll post new instructions below..

**Comment by devbobo** [comment]
1. Download and install Hesperus from the App Store
2. Launch Hesperus
3. Click the Settings icon

![image](https://cloud.githubusercontent.com/assets/680871/20088437/279f791c-a5d4-11e6-8eea-79465926dd7c.png)
4. Select `Accessories`

![image](https://cloud.githubusercontent.com/assets/680871/20088485/68cb4ac4-a5d4-11e6-9b12-20ebddd8d401.png)
5. Swipe left on `Homebridge`

![image](https://cloud.githubusercontent.com/assets/680871/20088519/9a118792-a5d4-11e6-813e-1969f6e602f5.png)
6. Select `Config`

![image](https://cloud.githubusercontent.com/assets/680871/20088671/d97c1d38-a5d5-11e6-8630-bc48aa81bf62.png)
7. Select `Manage Platform`

![image](https://cloud.githubusercontent.com/assets/680871/20088710/159e2f9a-a5d6-11e6-8550-f784ecbb7a5a.png)
8. Select `LifxLan`

![image](https://cloud.githubusercontent.com/assets/680871/20088872/2487ba84-a5d7-11e6-8b64-00b3265ced2b.png)
9. Select `Remove Accessory`
10. Select the accessory to remove and then click `Next`



Let me know if you have any questions.

**Comment by gregorfd** [comment]
Removed the accessory as described above.  Added the new version  and it now works.  A color option is available and I can successfully change both color and brightness of the LIFX bulb via the "Home" app.

thanks for jumping on this so quickly.

**Comment by fiddypal** [comment]
@gregorfd updated to latest version doing "npm update -g" and i am getting the following error when i try to remove the light using the app you suggested:

```
(node:824) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.
[11/29/2016, 4:04:03 PM] [LiFx] Remove: Living Room Light 1
buffer.js:89
      throw new Error(
      ^

Error: If encoding is specified then the first argument must be a string
    at new Buffer (buffer.js:89:13)
    at ChannelCharacteristic.Characteristic.toHAP (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:274:15)
    at Service.Switch.Service.toHAP (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Service.js:201:44)
    at Accessory.toHAP (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:391:30)
    at Bridge.Accessory.toHAP (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:402:41)
    at Bridge.Accessory._updateConfiguration (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:504:23)
    at Bridge.Accessory.removeBridgedAccessories (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:305:8)
    at Server._handleUnregisterPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:463:16)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:43:10)
    at emitOne (events.js:96:13)

```

**Comment by fiddypal** [comment]
I dont know what this error did but now i can't even find the homebridge anymore!!!

I tried removing that app, removing home and reinstalling and now i can't find it when i search for a bridge to add :(

**Comment by fiddypal** [comment]
so i changed the mac address in the config.json file and now the bridge appears again... Has my iPhone or apple blocked the previous mac? What would cause that?

**Comment by fiddypal** [comment]
@gregorfd  can you share a screen cap of how you are changing the colors thru home app? I am not seeing that after updating to the latest code...

**Comment by gregorfd** [comment]
![img_5479](https://cloud.githubusercontent.com/assets/23297847/20724578/daaf9ae6-b63c-11e6-9c7b-0c3aa83a68f3.PNG)

hopefully this works.....

**Comment by gregorfd** [comment]
and this is what you see if you select "color"
![img_5480](https://cloud.githubusercontent.com/assets/23297847/20724654/13bf68a2-b63d-11e6-9c07-700fcd5de067.PNG)

**Comment by fiddypal** [comment]
You rock dude thanks! I do not have that button and am afraid to try removing again after that error which seems to have blacklisted the mac address assigned to the homebridge.

@devbobo any ideas?

I have done a fresh install and removed home from my device and all homes, shut off icloud etc, then resinstalled and added a new homebridge and i still cannot get the color button to show up.

**Comment by gregorfd** [comment]
yes, deep in some the help sites i found that an "instance" of homebridge can be held by your iphone.  the only way to clear it is to enter a "new" hex (just changing one letter/number).  then relaunching homebridge.  I removed LIFX-Lan per the directions above.  I downloaded the new version and via terminal entered the following command:
sudo npm install -g --unsafe-perm homebridge-lifx-lan

i checked that homebridge was working by typing "homebridge" in terminal.

once everything loaded up I closed the window terminating homebridge and then reenabled it using:
launchctl load ~/Library/LaunchAgents/com.github.homebridge.plist

closed terminal and then hit the app button on my phone.  and then waited for the magic to happen....

**Comment by fiddypal** [comment]
I tried to remove the lights via the app again and that crash error happened and blacklisted the mac again, so whatever that problem is blacklists the homebridge and i have to edit the mac for it to show up again. Ugh!

**Comment by devbobo** [comment]
This appears to be resolved now.

**Comment by ajwilkz** [comment]
@gregorfd could you please elaborate on:

yes, deep in some the help sites i found that an "instance" of homebridge can be held by your iphone. the only way to clear it is to enter a "new" hex (just changing one letter/number). then relaunching homebridge. 

Can you please tell me how to clear the "instance", and how do I enter a new hex? Where is this done, and which tools do I use? Thanks in advance!
