### ISSUE TITLE
WeMo and Lifx-Lan incompatible

### ISSUE THREAD

**Issue by Cyrelion** [devbobo/homebridge-lifx-lan#19]
Hi,

if you install the wemo-platform and the lifx-lan plugin together in one homebridge config you can't controll the wemo switches anymore. I can control the lifx and the wemo are shown in the home app, but I can't control them. The switch icon in the home app changes the status, but nothing happen. But If I remove the lifx-lan platform from the config the wemo's work again.

**Comment by devbobo** [comment]
@Cyrelion hmm, this isn't true....I run both of these platforms on my RPi at home without issue, as well as writing the code for both plugins.

There must be some other issue.

**Comment by Cyrelion** [comment]
Hm, okay, I'll retest with a clean install. Thanks for the feedback.
