### ISSUE TITLE
Homebridge crashing when I access the Home IOS app 

### ISSUE THREAD

**Issue by davidbutler62** [devbobo/homebridge-lifx-lan#22]
My setup has been working for months, but today I ran into a problem

I have six Lifx bulbs and i am running homebridge with just the homebridge-lifx-lan plugin

Siri is still working fine, but when i access the Home app all the bulbs are shown as not responding.  When i check my homebridge logs i see the following the moment i access the home app

Dec 11 15:27:12 raspberrypi homebridge[23287]: /usr/local/lib/node_modules/homebridge-lifx-lan/index.js:595
Dec 11 15:27:12 raspberrypi homebridge[23287]: service.getCharacteristic(Characteristic.Brightness).updateValue(this.color.brightness);
Dec 11 15:27:12 raspberrypi homebridge[23287]: ^
Dec 11 15:27:12 raspberrypi homebridge[23287]: TypeError: service.getCharacteristic(...).updateValue is not a function
Dec 11 15:27:12 raspberrypi homebridge[23287]: at LifxAccessory.<anonymous> (/usr/local/lib/node_modules/homebridge-lifx-lan/index.js:595:74)
Dec 11 15:27:12 raspberrypi homebridge[23287]: at Client.<anonymous> (/usr/local/lib/node_modules/homebridge-lifx-lan/node_modules/node-lifx/lib/lifx/light.js:206:5)
Dec 11 15:27:12 raspberrypi homebridge[23287]: at Client.<anonymous> (/usr/local/lib/node_modules/homebridge-lifx-lan/node_modules/node-lifx/lib/lifx/client.js:355:26)
Dec 11 15:27:12 raspberrypi homebridge[23287]: at Array.forEach (native)
Dec 11 15:27:12 raspberrypi homebridge[23287]: at Client.processMessageHandlers (/usr/local/lib/node_modules/homebridge-lifx-lan/node_modules/node-lifx/lib/lifx/client.js:341:24)
Dec 11 15:27:12 raspberrypi homebridge[23287]: at Client.<anonymous> (/usr/local/lib/node_modules/homebridge-lifx-lan/node_modules/node-lifx/lib/lifx/client.js:178:12)
Dec 11 15:27:12 raspberrypi homebridge[23287]: at emitTwo (events.js:87:13)
Dec 11 15:27:12 raspberrypi homebridge[23287]: at Socket.emit (events.js:172:7)
Dec 11 15:27:12 raspberrypi homebridge[23287]: at UDP.onMessage (dgram.js:481:8)
Dec 11 15:27:12 raspberrypi systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE
Dec 11 15:27:12 raspberrypi systemd[1]: Unit homebridge.service entered failed state.

Anyone got any ideas?   I am running the latest version of the plugin

**Comment by davidbutler62** [comment]
Strange thing is that the Hesperus app does not cause this issue.  

But the Apple Home app, the original Home app and the Eve app all cause my homebridge to crash at startup

**Comment by davidbutler62** [comment]
Correction.  Hesperus is now causing the same problem when i first open it

**Comment by devbobo** [comment]
sorry for the radio silence, I've had other work and xmas commitments. I've rolled back to using the older style classes and things appear to be working correctly again for me.

Please try working 0.1.9

**Comment by davidbutler62** [comment]
Hi.  I am still having the same issue with 0.1.9 :-(

Dec 21 15:14:03 raspberrypi homebridge[322]: Wed, 21 Dec 2016 15:14:03 GMT HAPServer [CC:22:3D:E3:CE:30] HAP Request: GET /characteristics?id=7.8
Dec 21 15:14:03 raspberrypi homebridge[322]: Wed, 21 Dec 2016 15:14:03 GMT Accessory [Homebridge] Getting value for Characteristic "On"
Dec 21 15:14:03 raspberrypi homebridge[322]: /usr/local/lib/node_modules/homebridge-lifx-lan/index.js:594
Dec 21 15:14:03 raspberrypi homebridge[322]: service.getCharacteristic(Characteristic.Brightness).updateValue(this.color.brightness);
Dec 21 15:14:03 raspberrypi homebridge[322]: ^
Dec 21 15:14:03 raspberrypi homebridge[322]: TypeError: service.getCharacteristic(...).updateValue is not a function
Dec 21 15:14:03 raspberrypi homebridge[322]: at LifxAccessory.<anonymous> (/usr/local/lib/node_modules/homebridge-lifx-lan/index.js:594:70)
Dec 21 15:14:03 raspberrypi homebridge[322]: at Client.<anonymous> (/usr/local/lib/node_modules/homebridge-lifx-lan/node_modules/node-lifx/lib/lifx/light.js:206:5)
Dec 21 15:14:03 raspberrypi homebridge[322]: at Client.<anonymous> (/usr/local/lib/node_modules/homebridge-lifx-lan/node_modules/node-lifx/lib/lifx/client.js:355:26)
Dec 21 15:14:03 raspberrypi homebridge[322]: at Array.forEach (native)
Dec 21 15:14:03 raspberrypi homebridge[322]: at Client.processMessageHandlers (/usr/local/lib/node_modules/homebridge-lifx-lan/node_modules/node-lifx/lib/lifx/client.js:341:24)
Dec 21 15:14:03 raspberrypi homebridge[322]: at Client.<anonymous> (/usr/local/lib/node_modules/homebridge-lifx-lan/node_modules/node-lifx/lib/lifx/client.js:178:12)
Dec 21 15:14:03 raspberrypi homebridge[322]: at emitTwo (events.js:87:13)
Dec 21 15:14:03 raspberrypi homebridge[322]: at Socket.emit (events.js:172:7)
Dec 21 15:14:03 raspberrypi homebridge[322]: at UDP.onMessage (dgram.js:481:8)
Dec 21 15:14:03 raspberrypi systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE
Dec 21 15:14:03 raspberrypi systemd[1]: Unit homebridge.service entered failed state.
Dec 21 15:14:13 raspberrypi systemd[1]: homebridge.service holdoff time over, scheduling restart.
Dec 21 15:14:13 raspberrypi systemd[1]: Stopping Node.js HomeKit Server...

Could it be something to do with the latest lifx firmware or a particular bulb?

**Comment by devbobo** [comment]
@davidbutler62 what version of Homebridge are you running on ? I'd make sure you are running the latest version.

**Comment by davidbutler62** [comment]
I updated homebridge and now the issue has gone!   Thanks.  I had only been updating the life-lan package and not homebridge, so my bad :)

Thanks for your support

Cheers

Dave
