### ISSUE TITLE
Kelvin support?

### ISSUE THREAD

**Issue by cmsimike** [devbobo/homebridge-lifx-lan#23]
Hi - thank you SO MUCH for this! I love being able to control my lights from my apple devices!
I see on the homepage you mention support for Kelvin however I've not been able to get siri to change the temperature of my lights. 

Do you happen to know how to do that?

**Comment by devbobo** [comment]
@cmsimike `Kelvin` is defined as a custom characteristic as HomeKit doesn't a built-in one, therefore, the `Kelvin` attribute can be adjusted manually using some 3rd party HomeKit apps, but unfortunately not using Siri.

**Comment by cmsimike** [comment]
Thank you!
