### ISSUE TITLE
Question: How to remove lifx bulb from homebridge ?

### ISSUE THREAD

**Issue by maragelis** [devbobo/homebridge-lifx-lan#24]
Is there a way to remove a lifx bulb from homebridge? I have 10 bulbs and had to change one out how would someone delete a non existing bulb. Thanks

**Comment by devbobo** [comment]
I've add a [wiki article](https://github.com/devbobo/homebridge-lifx-lan/wiki/Removing-a-bulb-from-Homebridge) for this.

**Comment by maragelis** [comment]
Thanks a lot
