### ISSUE TITLE
No bulbs discovered

### ISSUE THREAD

**Issue by ronzelver** [devbobo/homebridge-lifx-lan#3]
Hi,
I've installed the plugin on a working homebridge system on my FreeBSD 10 NAS.
The startup output log looks fine to me:

`[Wed Mar 16 2016 19:33:17 GMT+0000 (UTC)] [LiFx] Initializing LifxLan platform...
[Wed Mar 16 2016 19:33:17 GMT+0000 (UTC)] [Harmony Hub Woonkamer] Initializing HarmonyHub platform...
Using Logitech Harmony hub ip address from configuration
[Wed Mar 16 2016 19:33:17 GMT+0000 (UTC)] [Harmony Hub Woonkamer] Connecting to Logitech Harmony remote hub...
[Wed Mar 16 2016 19:33:17 GMT+0000 (UTC)] Initializing HomeWizard platform...
[Wed Mar 16 2016 19:33:17 GMT+0000 (UTC)] Loading 1 accessories...
[Wed Mar 16 2016 19:33:17 GMT+0000 (UTC)] [thermostaat] Initializing NefitEasy accessory...
[Wed Mar 16 2016 19:33:17 GMT+0000 (UTC)] [LiFx] Server Listening...` 

But after a good startup of homebridge the LiFx plugin does not discover my bulb, and consequently no bulbs are advertised with homebridge.
Where do I have to look for this problem?

**Comment by beev** [comment]
Have you linked homebridge to a HomeKit compatible app?

**Comment by ronzelver** [comment]
Yes, i have linked it to both Insteon+ and MyTouchHome

**Comment by devbobo** [comment]
@ronzelver are the lifx bulbs on the same subnet as the homebridge server ?

**Comment by ronzelver** [comment]
Yes, the bulb is on the same subnet

**Comment by devbobo** [comment]
can you please try the following...
1. from the command line, goto the `homebridge-lifx-lan` directory
2. run `node node_modules/node-lifx/cli.js`

Does that show up any devices ?

**Comment by ronzelver** [comment]
This is the output from  `node node_modules/node-lifx/cli.js`:

` [root@saclnas04 ~/node_modules/homebridge-lifx-lan]# node node_modules/node-lifx/cli.js
LIFX Client UDP packet error
Trace: { [Error: bind EADDRINUSE 0.0.0.0:56700]
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'bind',
  address: '0.0.0.0',
  port: 56700 }
    at Client.<anonymous> (/root/node_modules/homebridge-lifx-lan/node_modules/node-lifx/lib/lifx/client.js:121:13)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at dgram.js:215:14
    at _combinedTickCallback (node.js:380:13)
    at process._tickCallback (node.js:401:11)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:141:18)
    at node.js:933:3
LIFX error:
Error: bind EADDRINUSE 0.0.0.0:56700
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at dgram.js:214:18
    at _combinedTickCallback (node.js:380:13)
    at process._tickCallback (node.js:401:11)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:141:18)
    at node.js:933:3
dgram.js:320
    throw new RangeError('Port should be > 0 and < 65536');
    ^

RangeError: Port should be > 0 and < 65536
    at Socket.send (dgram.js:320:11)
    at Client.sendingProcess (/root/node_modules/homebridge-lifx-lan/node_modules/node-lifx/lib/lifx/client.js:183:19)
    at wrapper [as _onTimeout](timers.js:275:11)
    at Timer.listOnTimeout (timers.js:92:15) `

**Comment by devbobo** [comment]
@ronzelver sorry, you will need to stop homebridge in order to run that

**Comment by ronzelver** [comment]
Ok, I've stopped homebridge, the output is now:
`Started LIFX listening on 0.0.0.0:56700

{ size: 100,
  addressable: true,
  tagged: false,
  origin: true,
  protocolVersion: 1024,
  source: '42524b52',
  target: 'd073d500ae66',
  reserved1: <Buffer 00 00>,
  site: 'LIFXV2',
  ackRequired: false,
  resRequired: false,
  sequence: 0,
  time: <Buffer 44 a0 10 29 f3 ff 3d 14>,
  type: 'echoResponse',
  reserved2: <Buffer 00 00>,
  payload: 'LIFX���7��=\u0014' } ' from 192.168.1.158'
{ size: 38,
  addressable: true,
  tagged: false,
  origin: true,
  protocolVersion: 1024,
  source: '42524b52',
  target: 'd073d500ae66',
  reserved1: <Buffer 00 00>,
  site: 'LIFXV2',
  ackRequired: false,
  resRequired: false,
  sequence: 0,
  time: <Buffer 04 86 6c 17 f4 ff 3d 14>,
  type: 'stateTemperature',
  reserved2: <Buffer 00 00>,
  temperature: 3800 } ' from 192.168.1.158'
{ size: 40,
  addressable: true,
  tagged: false,
  origin: true,
  protocolVersion: 1024,
  source: '42524b52',
  target: 'd073d500ae66',
  reserved1: <Buffer 00 00>,
  site: 'LIFXV2',
  ackRequired: false,
  resRequired: false,
  sequence: 0,
  time: <Buffer 04 42 0d 7d f5 ff 3d 14>,
  type: 406,
  reserved2: <Buffer 00 00> } ' from 192.168.1.158'`

**Comment by devbobo** [comment]
@MariusRumpf any ideas why this bulb wouldn't be being listed as a `New light` when the `cli.js` script is run ?

**Comment by devbobo** [comment]
@ronzelver if Marius doesn't reply here, you might try logging an issue on [his project](https://github.com/MariusRumpf/node-lifx) as his underlying framework is what I use for the Lifx bulb communications.

**Comment by ronzelver** [comment]
I got the `cli.js` working by adding a specific broadcast address in the `client.init()` call.
`client.init({
    broadcast: '192.168.1.255'
});`
I've added it in the `index.js` of the `homebridge-lifx-lan` as well, but still nothing?!

**Comment by devbobo** [comment]
@ronzelver I've released a new version (0.1.1) which updates the latest version of `node-lifx`. I've also exposed `broadcast` in the `config.json` so that you don't have to edit the `index.js`.

Please let me know how you get on.

**Comment by ronzelver** [comment]
@devbobo Thanks, it's working now, I can control my Lifx bulb with Homekit :-)
