### ISSUE TITLE
White color temp not working in Home app

### ISSUE THREAD

**Issue by starlessblack** [devbobo/homebridge-lifx-lan#30]
I'm not sure what caused this, but I'm thinking it probably started happening within the last few weeks: I'm generally unable to change white color temp on my color LIFX bulbs. Bizarrely, the Eve app is able to adjust color temp in white spectrum fine still (as is, of course, the stock LIFX app).

I briefly tried reverting back to ver. 0.2.2 because it appears that was the last version before a change in how the lifx-lan plugin handles color temp changes. But reverting to old plugin didn't make a difference.

Does anyone have any insight on this? Thank you.

**Comment by devbobo** [comment]
@starlessblack are you trying to set the `Color Temperature` using the `Home` app ? Try version 1.2.5 that I just published

**Comment by starlessblack** [comment]
Thank you for the quick response. I just updated to 1.2.5 (or 0.2.5?), and it has more or less fixed the odd behavior. It's still a little funky acting at times, but probably 90% better. The other 10% may be me picking color temps on the Home app's gradient wheel that don't actually exist in the Lifx API or something. Thanks, mate!

**Comment by devbobo** [comment]
@starlessblack yes, `0.2.5` (typo)...I need to convert from `mireds` to `kelvin` and visa versa between Homebridge and the LiFX bulbs so there could be some rounding weirdness there which accounts for the weirdness you may be seeing

**Comment by devbobo** [comment]
Reopen if this is still an issue.
