### ISSUE TITLE
Bulbs not showing up

### ISSUE THREAD

**Issue by tregusti** [devbobo/homebridge-lifx-lan#4]
Thank you for doing this plugin!

First off, everything worked. I could control my LIFX lamps with Siri. But then I wanted to try another iphone app, and I removed the homebridge connection from the iphone app, and wanted to try pairing again. But this time, without any changes in configuration, no lamps or and not even homebridge is showing up in the Home app.

I tried restarting both app, homebridge and phone some times. With no luck... The log looks fine, and I can see in Bonjour Browser that Homebridge is exposed there as it should.

Any Ideas?

**Comment by tregusti** [comment]
And now it works.

I don't what happened. Close this =)

**Comment by devbobo** [comment]
👍
