### ISSUE TITLE
When i change the bulb names... homebridge does NOT pickup the new name

### ISSUE THREAD

**Issue by cvee72** [devbobo/homebridge-lifx-lan#5]
Hi,
This is more a question.

I recently changed the name of some bulbs via the Lifx iphone app.
This change automatically propagated across all my ios devices.

When i restart homebridge... it still identifies the lights by their previous name.
I have tried removing the 'persist' folder and restarting homebridge... but it keeps returning the old bulb names.

Where is this being stored ?
How can i reset this data so that homebridge pulls the names from lifx ?

Thanks

**Comment by devbobo** [comment]
G'day @cvee72,

Sorry for the delayed response, currently homebridge doesn't support changing the name of a device, this apparently is a limitation of HomeKit. Devices need to be renamed within the HomeKit app rather than the device being able to rename themselves.

Hope this helps.

Cheers,

David
